-- cxj-blog initial schema (PostgreSQL 18+).
-- Managed by Flyway. Do not edit this file after it has been applied to a shared environment.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE sys_user (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  nickname VARCHAR(80) NOT NULL,
  avatar_url VARCHAR(1024),
  role VARCHAR(20) NOT NULL DEFAULT 'ADMIN' CHECK (role IN ('ADMIN', 'AUTHOR', 'READER')),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_sys_user_email_active ON sys_user (email) WHERE deleted_at IS NULL;

CREATE TABLE blog_category (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  description VARCHAR(500),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_blog_category_slug_active ON blog_category (slug) WHERE deleted_at IS NULL;

CREATE TABLE blog_tag (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_blog_tag_slug_active ON blog_tag (slug) WHERE deleted_at IS NULL;

CREATE TABLE blog_post (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES sys_user(id),
  category_id BIGINT REFERENCES blog_category(id),
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(240) NOT NULL,
  summary VARCHAR(500),
  content_md TEXT NOT NULL,
  content_html TEXT,
  cover_url VARCHAR(1024),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'OFFLINE')),
  is_top BOOLEAN NOT NULL DEFAULT FALSE,
  view_count BIGINT NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  seo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(content_md, ''))
  ) STORED,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_blog_post_slug_active ON blog_post (slug) WHERE deleted_at IS NULL;
CREATE INDEX idx_blog_post_public_list ON blog_post (status, is_top DESC, published_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_blog_post_search_vector ON blog_post USING GIN (search_vector);

CREATE TABLE blog_post_tag (
  post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES blog_tag(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, tag_id)
);
CREATE INDEX idx_blog_post_tag_tag_id ON blog_post_tag (tag_id);

CREATE TABLE blog_page (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(240) NOT NULL,
  content_md TEXT NOT NULL,
  content_html TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'OFFLINE')),
  seo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_blog_page_slug_active ON blog_page (slug) WHERE deleted_at IS NULL;

CREATE TABLE file_object (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uploader_id BIGINT REFERENCES sys_user(id),
  cos_key VARCHAR(1024) NOT NULL,
  public_url VARCHAR(2048),
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(255) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  sha256 CHAR(64),
  usage_type VARCHAR(30) NOT NULL DEFAULT 'GENERAL' CHECK (usage_type IN ('GENERAL', 'IMAGE', 'COVER', 'ATTACHMENT')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_file_object_cos_key ON file_object (cos_key);
CREATE INDEX idx_file_object_uploader_created ON file_object (uploader_id, created_at DESC);

CREATE TABLE operation_log (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES sys_user(id),
  action VARCHAR(100) NOT NULL,
  resource_type VARCHAR(50) NOT NULL,
  resource_id VARCHAR(64),
  ip INET,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_operation_log_operator_created ON operation_log (operator_id, created_at DESC);

CREATE TABLE analytics_event (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_name VARCHAR(50) NOT NULL,
  post_id BIGINT REFERENCES blog_post(id) ON DELETE SET NULL,
  visitor_id_hash CHAR(64),
  session_id VARCHAR(100),
  referer VARCHAR(2048),
  user_agent VARCHAR(1024),
  properties_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_analytics_event_name_time ON analytics_event (event_name, occurred_at DESC);
CREATE INDEX idx_analytics_event_post_time ON analytics_event (post_id, occurred_at DESC);

CREATE TRIGGER trg_sys_user_updated_at BEFORE UPDATE ON sys_user FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_blog_category_updated_at BEFORE UPDATE ON blog_category FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_blog_tag_updated_at BEFORE UPDATE ON blog_tag FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_blog_post_updated_at BEFORE UPDATE ON blog_post FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_blog_page_updated_at BEFORE UPDATE ON blog_page FOR EACH ROW EXECUTE FUNCTION set_updated_at();
